name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

#    runs-on: ubuntu-latest
    runs-on: [self-hosted, runner-2]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Write secret to resource
      env:
        KEY: ${{ secrets.TOP_SECRET }}
      run: echo $KEY > output/secret.txt

    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Execute
      run: dotnet run 
      env:
        KEY: ${{ secrets.TOP_SECRET }}

    - name: Get secret
      env:
        KEY: ${{ secrets.TOP_SECRET }}
      run: echo $KEY > output/shh.txt

    - name: Publish
      run: dotnet publish secret.csproj -p:PublishProfile=Development --no-restore --output output

    - name: Setup JFrog CLI
    # You may pin to the exact commit or the version.
    # uses: jfrog/setup-jfrog-cli@11ee3f9bb82595485cb55670e4f93885080e183b
      uses: jfrog/setup-jfrog-cli@v2.4.1
      with:
      # JFrog CLI Version
        version: 2.24.2
      # Remote repository in Artifactory pointing to 'https://releases.jfrog.io/artifactory/jfrog-cli'. Use this parameter in case you don't have an Internet access.
      #  download-repository: # optional
    - name: Check JFrog CLI version
      run: jf --version
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output-secret
        path: output
        retention-days: 30

    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.2.0
      with:
        version: latest

    - name: list-octopusdeploy-deployments
      run: >
        octo list-deployments --server=http://localhost:8080
        --apiKey=${{ secrets.OCTO_APIKEY }}
      env:
        ServerUri: ${{ secrets.OCTO_SERVERURL }}

    - name: Octopus Package...
      run: octo pack --id="OctoConsole" --version="0.0.1" --basePath="output" --outFolder="octopackage" --format=zip

    - name: Archive Octopus Package
      uses: actions/upload-artifact@v3
      with:
        name: zip-package
        path: octopackage
        retention-days: 5








